In [ ]:
pip install pandas

In [6]:
import pandas as pd

In [ ]:
s = pd.Series([10, 20, 30, 40, 50])
print(s)

In [8]:
dados = pd.read_csv(r'C:\Users\logonrmlocal\Desktop\bicho_e_burro\ComputationalThinkingWhitPython\ComputationalThinkingWhitPython\Segundo Semestre\terceira_aula_26-02-24\dados\manutencao_preditiva.csv')

dados

UDI ID Produto Tipo  Temperatura Ar [K]  Temperatura Processo [K]  \
0         1     M14860    M               298.1                     308.6   
1         2     L47181    L               298.2                     308.7   
2         3     L47182    L               298.1                     308.5   
3         4     L47183    L               298.2                     308.6   
4         5     L47184    L               298.2                     308.7   
...     ...        ...  ...                 ...                       ...   
9995   9996     M24855    M               298.8                     308.4   
9996   9997     H39410    H               298.9                     308.4   
9997   9998     M24857    M               299.0                     308.6   
9998   9999     H39412    H               299.0                     308.7   
9999  10000     M24859    M               299.0                     308.7   

      Velocidade Rotacao [rpm]  Torque [Nm]  Desgaste Ferramenta [min]  Alvo  \
0                         1551         42.8                          0     0   
1                         1408         46.3                          3     0   
2                         1498         49.4                          5     0   
3                         1433         39.5                          7     0   
4                         1408         40.0                          9     0   
...                        ...          ...                        ...   ...   
9995                      1604         29.5                         14     0   
9996                      1632         31.8                         17     0   
9997                      1645         33.4                         22     0   
9998                      1408         48.5                         25     0   
9999                      1500         40.2                         30     0   

     Tipo da Falha  
0       No Failure  
1       No Failure  
2       No Failure  
3       No Failure  
4       No Failure  
...            ...  
9995    No Failure  
9996    No Failure  
9997    No Failure  
9998    No Failure  
9999    No Failure  

[10000 rows x 10 columns]

In [9]:
input =  dados[['Temperatura Ar [K]', 'Temperatura Processo [K]', 'Velocidade Rotacao [rpm]', 'Torque [Nm]', 'Desgaste Ferramenta [min]']]
output = dados['Tipo da Falha']

In [ ]:
pip install --upgrade scikit-learn

In [10]:
from sklearn.model_selection import train_test_split

xtreino, xteste, ytreino, yteste = train_test_split(input, output, test_size = 0.3)

In [16]:
xtreino

Temperatura Ar [K]  Temperatura Processo [K]  Velocidade Rotacao [rpm]  \
9595               299.0                     310.1                      1432   
4860               303.6                     312.4                      1504   
9491               299.0                     309.7                      1489   
4797               303.5                     312.5                      1380   
6776               301.3                     310.6                      1451   
...                  ...                       ...                       ...   
3673               302.3                     311.7                      1449   
2107               299.4                     309.1                      1417   
9542               299.6                     310.9                      1716   
9723               298.8                     309.8                      1599   
662                297.6                     308.9                      1479   

      Torque [Nm]  Desgaste Ferramenta [min]  
9595         50.0                         45  
4860         49.5                        109  
9491         40.7                        212  
4797         46.1                        166  
6776         47.5                         42  
...           ...                        ...  
3673         44.5                        152  
2107         47.3                         59  
9542         28.5                        117  
9723         33.6                        131  
662          38.1                        182  

[7000 rows x 5 columns]

In [24]:
ytreino

9595    No Failure
4860    No Failure
9491    No Failure
4797    No Failure
6776    No Failure
           ...    
3673    No Failure
2107    No Failure
9542    No Failure
9723    No Failure
662     No Failure
Name: Tipo da Falha, Length: 7000, dtype: object

In [13]:
dados['Tipo da Falha'].value_counts()

Tipo da Falha
No Failure                  9652
Heat Dissipation Failure     112
Power Failure                 95
Overstrain Failure            78
Tool Wear Failure             45
Random Failures               18
Name: count, dtype: int64

In [15]:
from sklearn.neural_network import MLPClassifier

modelo = MLPClassifier(hidden_layer_sizes=(100), max_iter=100, activation='relu', verbose=1)

In [18]:
modelo.fit(xtreino, ytreino)

Iteration 1, loss = 18.02305247
Iteration 2, loss = 1.28727785
Iteration 3, loss = 1.26239329
Iteration 4, loss = 1.01045305
Iteration 5, loss = 0.76364023
Iteration 6, loss = 0.61930482
Iteration 7, loss = 0.50613703
Iteration 8, loss = 0.45853907
Iteration 9, loss = 0.39905203
Iteration 10, loss = 0.37463872
Iteration 11, loss = 0.30477384
Iteration 12, loss = 0.28716960
Iteration 13, loss = 0.27370365
Iteration 14, loss = 0.26437799
Iteration 15, loss = 0.26672828
Iteration 16, loss = 0.25985309
Iteration 17, loss = 0.24615034
Iteration 18, loss = 0.23382062
Iteration 19, loss = 0.24349279
Iteration 20, loss = 0.24395075
Iteration 21, loss = 0.23395434
Iteration 22, loss = 0.21637397
Iteration 23, loss = 0.20253623
Iteration 24, loss = 0.22063023
Iteration 25, loss = 0.22303682
Iteration 26, loss = 0.19607886
Iteration 27, loss = 0.19120951
Iteration 28, loss = 0.20182882
Iteration 29, loss = 0.20161533
Iteration 30, loss = 0.19064519
Iteration 31, loss = 0.16719698
Iteration 32, lo

MLPClassifier(hidden_layer_sizes=100, max_iter=100, verbose=1)

In [19]:
ypredicao = modelo.predict(xteste)

In [20]:
ypredicao

array(['No Failure', 'No Failure', 'No Failure', ..., 'No Failure',
       'No Failure', 'No Failure'], dtype='<U24')

In [22]:
ypred = pd.Series(ypredicao)
ypred.value_counts()

No Failure                  2988
Power Failure                 10
Heat Dissipation Failure       1
Overstrain Failure             1
Name: count, dtype: int64

In [23]:
yteste.value_counts()

Tipo da Falha
No Failure                  2902
Heat Dissipation Failure      37
Power Failure                 30
Overstrain Failure            15
Tool Wear Failure             12
Random Failures                4
Name: count, dtype: int64

In [26]:
s1 = pd.Series([10, 20, 30, 40, 50], name='Série 1')
s2 = pd.Series([1, 2, 3, 4, 5], name='Série 2')

In [31]:
soma = s1 + s2
print('Soma:')
print(soma)

Soma:
0    11
1    22
2    33
3    44
4    55
dtype: int64


In [32]:
subtracao = s1 - s2
print('Subtralção')
print(subtracao)

Subtralção
0     9
1    18
2    27
3    36
4    45
dtype: int64


In [33]:
multiplicacao = s1 * s2
print('Multiplicação')
print(multiplicacao)

Multiplicação
0     10
1     40
2     90
3    160
4    250
dtype: int64


In [34]:
divisao = s1 / s2
print('Divisão')
print(divisao)

Divisão
0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
dtype: float64


In [35]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [37]:
df = pd.DataFrame({'Séries 1':s1, 'Séries 2':s2})
df

Séries 1  Séries 2
0        10         1
1        20         2
2        30         3
3        40         4
4        50         5

In [38]:
import numpy as np

In [39]:
arr = np.array([[1,2,3], [4,5,6]])

result= arr * 2

In [40]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
result

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [42]:
import pandas as pd

In [45]:
data = {'A':[1, 2, 3], 'B':[4, 5, 6]}
df = pd.DataFrame(data)

df['C'] = df['A'] + df['B']

In [46]:
df

A  B  C
0  1  4  5
1  2  5  7
2  3  6  9

In [47]:
arr = np.array([1,2,3,4,5])

matriz = np.array([[1,2],[3,4]])
vetor = np.array([5,6])

produto_escalar = np.dot(matriz, vetor)
produto_escalar

array([17, 39])